import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Plus } from 'lucide-react';
import { useDashboard } from './inventory-api';
import { dateLabel, isExit, presentProduct, stockStatus, typeLabels, unitCodes } from './inventory-model';
import { DataState } from './data-controls';
import { ProductIdentity, Status, StockMeter } from './inventory-ui';

export function Overview() {
  const query = useDashboard();
  const summary = query.data;
  const [chartDay, setChartDay] = useState<string | null>(null);
  const scale = Math.max(1, ...(summary?.days.flatMap(day => [day.entryRecords, day.exitRecords]) ?? []));
  const attention = (summary?.low ?? 0) + (summary?.out ?? 0);
  return <DataState pending={query.isPending} error={query.error} retry={query.refetch}>{summary && <div className="overview-page">
    <div className="catalog-actions"><span>Posição atual do estoque</span><div className="inline-actions"><Link className="primary-button" to="/products/new"><Plus size={16} aria-hidden="true" />Novo produto</Link><Link className="secondary-button" to="/movements">Movimentar estoque</Link></div></div>
    <div className="dashboard-grid">
      <section className="hero-stock" aria-labelledby="stock-title"><div className="hero-topline"><span className="block-label">POSIÇÃO ATUAL</span></div><div className="hero-main"><h2 id="stock-title">Produtos ativos</h2><div className="hero-value">{summary.products}<span>produtos</span></div><p>{summary.normal + summary.low} com saldo disponível no catálogo</p></div><div className="hero-spectrum" role="img" aria-label={`${summary.normal} normais, ${summary.low} baixos, ${summary.out} zerados`}><span className="spectrum-success" style={{ flex: summary.normal }} /><span className="spectrum-warning" style={{ flex: summary.low }} /><span className="spectrum-danger" style={{ flex: summary.out }} /></div><div className="hero-legend"><span>{summary.normal} normais</span><span>{summary.low} baixos</span><span>{summary.out} zerados</span></div></section>
      <section className={'risk-panel' + (attention === 0 ? ' risk-clear' : '')} aria-labelledby="risk-title"><div className="risk-topline"><span className="block-label">{attention === 0 ? 'ESTOQUE SOB CONTROLE' : 'ALERTAS DE ESTOQUE'}</span></div><div><h2 id="risk-title">{attention === 0 ? 'Nenhum produto em atenção' : 'Requerem atenção'}</h2><div className="risk-value">{summary.low + summary.out}<span>produtos</span></div></div><div className="risk-breakdown"><span><strong>{summary.low}</strong> até o mínimo</span><span><strong>{summary.out}</strong> sem estoque</span></div><Link className="panel-link" to={attention === 0 ? '/products' : '/products?stock=attention'}>{attention === 0 ? 'Consultar catálogo' : 'Ver produtos em atenção'}<ArrowUpRight size={17} /></Link></section>
      <section className="activity-panel" aria-labelledby="activity-title"><div className="dark-panel-heading"><span className="block-label">FLUXO RECENTE</span></div><h2 id="activity-title">Atividade recente</h2><p className="panel-subtitle">Entradas, saídas e ajustes</p><div className="activity-list">{summary.recent.map(movement => <div className={'activity-row activity-row-' + (isExit(movement.type) ? 'out' : 'in')} key={movement.id}><span className="activity-product">{movement.product.name}<small>{typeLabels[movement.type]} · {dateLabel(movement.createdAt)}</small></span><strong className={isExit(movement.type) ? 'out-text' : 'in-text'}>{isExit(movement.type) ? '−' : '+'}{movement.quantity} <small>{unitCodes[movement.product.unit]}</small></strong></div>)}{summary.recent.length === 0 && <p className="panel-subtitle">Nenhuma movimentação registrada.</p>}</div><Link className="activity-link" to="/history">Todas as movimentações <ArrowRight size={16} /></Link></section>
      <section className="attention-panel" aria-labelledby="attention-title"><div className="dark-panel-heading"><span className="block-label">FILA DE ATENÇÃO</span><Link className="icon-button" to="/products?stock=attention" aria-label="Ver produtos que precisam de atenção"><ArrowUpRight size={18} /></Link></div><h2 id="attention-title">Prioridades de reposição</h2><div className="attention-list">{summary.priorities.map(record => { const product = presentProduct(record); return <div className="attention-row" key={product.id}><ProductIdentity product={product} /><span className="attention-meter"><StockMeter stock={product.stock} minimum={product.minimum} name={product.name} /><small>{record.stock} {product.unit} / mín. {record.minimumStock}</small></span><Status {...stockStatus(product.stock, product.minimum)} /></div>; })}{summary.priorities.length === 0 && <p className="panel-subtitle">Nenhum produto precisa de reposição.</p>}</div></section>
    </div>
    <section className="dashboard-operational" aria-label="Resumo operacional"><div className="cost-summary"><span className="block-label">VALOR A CUSTO</span><strong>{Number(summary.costValue).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong><small>{summary.productsWithoutCost} {summary.productsWithoutCost === 1 ? 'produto sem custo informado, excluído' : 'produtos sem custo informado, excluídos'} do valor.</small></div><div className="day-summary"><h2>Movimentos hoje</h2><span>Entradas <strong>{summary.today.entries}</strong></span><span>Saídas <strong>{summary.today.exits}</strong></span><span>Ajustes <strong>{summary.today.adjustments}</strong></span></div><div className="week-summary"><h2>Entradas × Saídas · 7 dias</h2><p>Número de movimentações · entradas e saídas</p><div className="week-chart" aria-label="Movimentações por dia">{summary.days.map(day => <div className="chart-day" key={day.date}><button type="button" className="chart-trigger" aria-label={`${day.date.split('-').reverse().join('/')}: ${day.entryRecords} entradas e ${day.exitRecords} saídas`} aria-describedby={chartDay === day.date ? 'chart-tooltip-' + day.date : undefined} onMouseEnter={() => setChartDay(day.date)} onMouseLeave={() => setChartDay(null)} onFocus={() => setChartDay(day.date)} onBlur={() => setChartDay(null)} onClick={() => setChartDay(day.date)} onKeyDown={event => { if (event.key === 'Escape') { event.stopPropagation(); setChartDay(null); } }}><span className="week-bars" aria-hidden="true"><i style={{ height: day.entryRecords / scale * 56 }} /><b style={{ height: day.exitRecords / scale * 56 }} /></span><small>{day.date.slice(8,10)}/{day.date.slice(5,7)}</small></button>{chartDay === day.date && <div className="chart-tooltip" role="tooltip" id={'chart-tooltip-' + day.date}><strong>{day.date.split('-').reverse().join('/')}</strong><span>Entradas: {day.entryRecords}</span><span>Saídas: {day.exitRecords}</span></div>}</div>)}</div></div></section>
  </div>}</DataState>;
}
