import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight } from 'lucide-react';
import { useDashboard } from './inventory-api';
import { dateLabel, isExit, presentProduct, stockStatus, typeLabels, unitCodes } from './inventory-model';
import { DataState } from './data-controls';
import { ProductIdentity, Status, StockMeter } from './inventory-ui';

export function Overview() {
  const query = useDashboard();
  const summary = query.data;
  const scale = Math.max(1, ...(summary?.days.flatMap(day => [Number(day.entries), Number(day.exits)]) ?? []));
  return <DataState pending={query.isPending} error={query.error} retry={query.refetch}>{summary && <div className="overview-page">
    <div className="catalog-actions"><span>Posição atual do estoque</span><div className="inline-actions"><Link className="text-button" to="/products/new">Novo produto</Link><Link className="secondary-button" to="/movements">Movimentar estoque</Link></div></div>
    <div className="dashboard-grid">
      <section className="hero-stock" aria-labelledby="stock-title"><div className="hero-topline"><span className="block-label">POSIÇÃO ATUAL</span></div><div className="hero-main"><h2 id="stock-title">Unidades em estoque</h2><div className="hero-value">{Number(summary.units).toLocaleString('pt-BR', { maximumFractionDigits: 3 })}<span>un.</span></div><p>{summary.products} produtos ativos no catálogo</p></div><div className="hero-spectrum" role="img" aria-label={`${summary.normal} normais, ${summary.low} baixos, ${summary.out} zerados`}><span className="spectrum-success" style={{ flex: summary.normal }} /><span className="spectrum-warning" style={{ flex: summary.low }} /><span className="spectrum-danger" style={{ flex: summary.out }} /></div><div className="hero-legend"><span>{summary.normal} normais</span><span>{summary.low} baixos</span><span>{summary.out} zerados</span></div></section>
      <section className="risk-panel" aria-labelledby="risk-title"><div className="risk-topline"><span className="block-label">ALERTAS DE ESTOQUE</span></div><div><h2 id="risk-title">Requerem atenção</h2><div className="risk-value">{summary.low + summary.out}<span>produtos</span></div></div><div className="risk-breakdown"><span><strong>{summary.low}</strong> até o mínimo</span><span><strong>{summary.out}</strong> sem estoque</span></div><Link className="panel-link" to="/products?stock=attention">Ver produtos em atenção <ArrowUpRight size={17} /></Link></section>
      <section className="activity-panel" aria-labelledby="activity-title"><div className="dark-panel-heading"><span className="block-label">FLUXO RECENTE</span></div><h2 id="activity-title">Atividade recente</h2><p className="panel-subtitle">Entradas, saídas e ajustes</p><div className="activity-list">{summary.recent.map(movement => <div className={'activity-row activity-row-' + (isExit(movement.type) ? 'out' : 'in')} key={movement.id}><span className="activity-product">{movement.product.name}<small>{typeLabels[movement.type]} · {dateLabel(movement.createdAt)}</small></span><strong className={isExit(movement.type) ? 'out-text' : 'in-text'}>{isExit(movement.type) ? '−' : '+'}{movement.quantity} <small>{unitCodes[movement.product.unit]}</small></strong></div>)}{summary.recent.length === 0 && <p className="panel-subtitle">Nenhuma movimentação registrada.</p>}</div><Link className="activity-link" to="/history">Todas as movimentações <ArrowRight size={16} /></Link></section>
      <section className="attention-panel" aria-labelledby="attention-title"><div className="dark-panel-heading"><span className="block-label">FILA DE ATENÇÃO</span><Link to="/products?stock=attention" aria-label="Ver produtos que precisam de atenção"><ArrowUpRight size={18} /></Link></div><h2 id="attention-title">Prioridades de reposição</h2><div className="attention-list">{summary.priorities.map(record => { const product = presentProduct(record); return <div className="attention-row" key={product.id}><ProductIdentity product={product} /><span className="attention-meter"><StockMeter stock={product.stock} minimum={product.minimum} name={product.name} /><small>{record.stock} {product.unit} / mín. {record.minimumStock}</small></span><Status {...stockStatus(product.stock, product.minimum)} /></div>; })}{summary.priorities.length === 0 && <p className="panel-subtitle">Nenhum produto precisa de reposição.</p>}</div></section>
    </div>
    <section className="dashboard-operational" aria-label="Resumo operacional"><div className="cost-summary"><span className="block-label">VALOR A CUSTO</span><strong>{Number(summary.costValue).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</strong><small>{summary.productsWithoutCost} produtos sem custo informado, excluídos do valor.</small></div><div className="day-summary"><h2>Movimentos hoje</h2><span>Entradas <strong>{summary.today.entries}</strong></span><span>Saídas <strong>{summary.today.exits}</strong></span><span>Ajustes <strong>{summary.today.adjustments}</strong></span></div><div className="week-summary"><h2>Entradas × Saídas · 7 dias</h2><p>Quantidades registradas · verde: entradas, vermelho: saídas</p><div className="week-chart" role="img" aria-label={summary.days.map(day => `${day.date}: entradas ${day.entries}, saídas ${day.exits}`).join('; ')}>{summary.days.map(day => <div key={day.date}><span className="week-bars"><i style={{ height: Number(day.entries) / scale * 56 }} /><b style={{ height: Number(day.exits) / scale * 56 }} /></span><small>{day.date.slice(8,10)}/{day.date.slice(5,7)}</small></div>)}</div></div></section>
  </div>}</DataState>;
}
